### ISSUE TITLE
Posted in Error

### ISSUE THREAD

**Issue by ezeasorekene** [matteocasonato/dex-listings-scanner-bot#1]
...

**Comment by ezeasorekene** [comment]
@0xCaso 

So sorry about this spam post. One of my account's personal access tokens was compromised so it was used to target multiple repos. I have now recovered my account and revoked the PAT. Apologies for any inconvenience.

You may wish to delete the entire thread, please.

**Comment by 0xCaso** [comment]
hey @ezeasorekene, no worries, and happy you managed to get your account back

I don't think issues are deletable though.
